### ISSUE TITLE
Black team screen

### ISSUE THREAD

**Issue by Thithic** [mchev/blinest#15]
Hello mchev, 
First of all, thank you for your work, just saw the v2.0 live today, it seems great !
I noticed a little bug regarding Teams: the first team created (team-du-midi) is unavailble. [https://blinest.com/teams/1](https://blinest.com/teams/1) gives a black screen with js error in the console 
```
TypeError: i.members.sort is not a function
    at setup (Show.37e97c0f.js:1:4704)
    at _n (app.ab0ca389.js:12:656)
    at av (app.ab0ca389.js:12:50262)
    at cp (app.ab0ca389.js:12:50047)
    at z (app.ab0ca389.js:12:37655)
    at Q (app.ab0ca389.js:12:37547)
    at O (app.ab0ca389.js:12:34377)
    at jo.K [as fn] (app.ab0ca389.js:12:38665)
    at jo.run (app.ab0ca389.js:9:24182)
    at x.update (app.ab0ca389.js:12:38940)
```

Maybe related : when the teams had only 2 members, the page was working correctly.

**Comment by mchev** [comment]
Thanks for the feedback.
It's now fixed.

The members list was an object and the find and sort function only works on array.
